In [4]:
import h2o
import pandas as pd
from h2o.automl import H2OAutoML
import re
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
from path import Path
import numpy as np

h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         1 min 35 secs
H2O_cluster_timezone:       Asia/Kolkata
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.30.0.1
H2O_cluster_version_age:    2 months and 17 days
H2O_cluster_name:           H2O_from_python_Arunodhaya_v1op42
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.979 Gb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.6.5 final
--------------------------  ---------------------------------------------------------

In [2]:
def ifnone(a,b):
    "`a` if `a` is not None, otherwise `b`."
    return b if a is None else a
def make_date(df, date_field):
    "Make sure `df[field_name]` is of the right date type."
    field_dtype = df[date_field].dtype
    if isinstance(field_dtype, pd.core.dtypes.dtypes.DatetimeTZDtype):
        field_dtype = np.datetime64
    if not np.issubdtype(field_dtype, np.datetime64):
        df[date_field] = pd.to_datetime(df[date_field], infer_datetime_format=True)
def add_datepart(df, field_name:str, prefix:str=None, drop:bool=True, time:bool=False):
    "Helper function that adds columns relevant to a date in the column `field_name` of `df`."
    make_date(df, field_name)
    field = df[field_name]
    prefix = ifnone(prefix, re.sub('[Dd]ate$', '', field_name))
    attr = ['Year', 'Month', 'Week', 'Day', 'Dayofweek', 'Dayofyear', 'Is_month_end', 'Is_month_start', 
            'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start']
    if time: attr = attr + ['Hour', 'Minute', 'Second']
    for n in attr: df[prefix + n] = getattr(field.dt, n.lower())
    df[prefix + 'Elapsed'] = field.astype(np.int64) // 10 ** 9
    if drop: df.drop(field_name, axis=1, inplace=True)
    return df

In [5]:

DIR=Path("Dataset/")
DIR.files()
(train, test) = pd.read_csv(DIR+"Train.csv"),pd.read_csv(DIR+"Test.csv")
add_datepart(test,"DATE").head()
add_datepart(train,"DATE").head()

[Path('Dataset/sample_submission.csv'),
 Path('Dataset/Test.csv'),
 Path('Dataset/Train.csv')]

,INCIDENT_ID,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,...,DATEDay,DATEDayofweek,DATEDayofyear,DATEIs_month_end,DATEIs_month_start,DATEIs_quarter_end,DATEIs_quarter_start,DATEIs_year_end,DATEIs_year_start,DATEElapsed
0,CR_195453,0,30,35,7,3,6,4,0,5,...,1,3,32,False,True,False,False,False,False,1517443200
1,CR_103520,0,44,44,1,3,7,1,4,6,...,5,4,65,False,False,False,False,False,False,1078444800
2,CR_196089,0,34,33,3,5,2,7,3,0,...,27,5,27,False,False,False,False,False,False,1517011200
3,CR_112195,7,3,2,3,5,9,8,0,5,...,18,4,230,False,False,False,False,False,False,1155859200
4,CR_149832,0,7,8,7,3,2,7,1,5,...,31,0,304,True,False,False,False,False,False,1320019200

,INCIDENT_ID,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,...,DATEDay,DATEDayofweek,DATEDayofyear,DATEIs_month_end,DATEIs_month_start,DATEIs_quarter_end,DATEIs_quarter_start,DATEIs_year_end,DATEIs_year_start,DATEElapsed
0,CR_102659,0,36,34,2,1,5,6,1,6,...,4,6,186,False,False,False,False,False,False,1088899200
1,CR_189752,1,37,37,0,0,11,17,1,6,...,18,1,199,False,False,False,False,False,False,1500336000
2,CR_184637,0,3,2,3,5,1,0,2,3,...,15,2,74,False,False,False,False,False,False,1489536000
3,CR_139071,0,33,32,2,1,7,1,1,6,...,13,4,44,False,False,False,False,False,False,1234483200
4,CR_109335,0,33,32,2,1,8,3,0,5,...,13,2,103,False,False,False,False,False,False,1113350400

In [15]:
ml1=h2o.load_model("../h2o/DRF_1_AutoML_20200621_151435")
#ml1.predict(test)

In [16]:
ml2=h2o.load_model("../h2o/XRT_1_AutoML_20200621_151435")
ml2

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  XRT_1_AutoML_20200621_151435


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,42.0,42.0,304546.0,20.0,20.0,20.0,363.0,817.0,573.8095

ModelMetricsBinomial: drf
** Reported on train data. **

MSE: 0.013015892433418235
RMSE: 0.11408721415398938
LogLoss: 0.059284189364747254
Mean Per-Class Error: 0.0286214112296439
AUC: 0.9948537003508648
AUCPR: 0.9996764600600524
Gini: 0.9897074007017297

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.6316536542881965:

              0        1   Error              Rate
0      0  899.0    169.0  0.1582    (169.0/1068.0)
1      1   64.0  22724.0  0.0028    (64.0/22788.0)
2  Total  963.0  22893.0  0.0098   (233.0/23856.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold         value    idx
0                        max f1   0.631654      0.994899  233.0
1                        max f2   0.509037      0.996735  268.0
2                  max f0point5   0.694542      0.995050  212.0
3                  max accuracy   0.634012      0.990233  232.0
4                 max precision   0.942109      0.999885   67.0
5                    max recall   0.166811      1.000000  364.0
6               max specificity   1.000000      0.998127    0.0
7              max absolute_mcc   0.669821      0.884877  220.0
8    max min_per_class_accuracy   0.818175      0.970974  158.0
9   max mean_per_class_accuracy   0.814365      0.971379  160.0
10                      max tns   1.000000   1066.000000    0.0
11                      max fns   1.000000  10219.000000    0.0
12                      max fps   0.000000   1068.000000  399.0
13                      max tps   0.166811  22788.000000  364.0
14                      max tnr   1.000000      0.998127    0.0
15                      max fnr   1.000000      0.448438    0.0
16                      max fpr   0.000000      1.000000  399.0
17                      max tpr   0.166811      1.000000  364.0

Gains/Lift Table: Avg response rate: 95.52 %, avg score: 94.45 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.526073,1.000000,1.046700,1.046700,0.999841,1.000000,0.999841,1.000000,0.550641,0.550641,4.669994,4.669994
1,,2,0.600059,0.997872,1.046867,1.046721,1.000000,0.998901,0.999860,0.999864,0.077453,0.628094,4.686677,4.672051
2,,3,0.699992,0.947557,1.046867,1.046741,1.000000,0.982975,0.999880,0.997453,0.104616,0.732710,4.686677,4.674139
3,,4,0.800008,0.933333,1.045551,1.046593,0.998743,0.939854,0.999738,0.990252,0.104573,0.837283,4.555051,4.659251
4,,5,0.901115,0.875000,1.042093,1.046088,0.995439,0.911881,0.999256,0.981459,0.105362,0.942645,4.209250,4.608760
5,,6,1.000000,0.000000,0.580015,1.000000,0.554048,0.607986,0.955231,0.944528,0.057355,1.000000,-41.998522,0.000000

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error
0,,2020-06-21 15:19:00,11.301 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-06-21 15:19:00,11.486 sec,5.0,0.176222,0.667495,0.874004,0.988683,1.035476,0.031720
2,,2020-06-21 15:19:01,11.715 sec,10.0,0.144733,0.228589,0.948829,0.995643,1.042775,0.021631
3,,2020-06-21 15:19:01,11.911 sec,15.0,0.128314,0.112011,0.972584,0.997760,1.044872,0.017035
4,,2020-06-21 15:19:01,12.133 sec,20.0,0.126295,0.082973,0.984006,0.998797,1.045936,0.013754
5,,2020-06-21 15:19:01,12.344 sec,25.0,0.120741,0.072948,0.988101,0.999133,1.046239,0.012451
6,,2020-06-21 15:19:01,12.545 sec,30.0,0.118459,0.066596,0.990881,0.999380,1.046487,0.011821
7,,2020-06-21 15:19:02,12.749 sec,35.0,0.115693,0.062031,0.993213,0.999562,1.046627,0.010186
8,,2020-06-21 15:19:02,12.959 sec,40.0,0.114645,0.059761,0.994656,0.999667,1.046701,0.009851
9,,2020-06-21 15:19:02,13.063 sec,42.0,0.114087,0.059284,0.994854,0.999676,1.046700,0.009767

Variable Importances:

         variable  relative_importance  scaled_importance  percentage
0            X_10          6352.489258           1.000000    0.225115
1            X_11          5967.083008           0.939330    0.211457
2            X_15          3394.160889           0.534304    0.120280
3            X_12          2420.453613           0.381024    0.085774
4     DATEElapsed           951.391418           0.149767    0.033715
5        DATEYear           809.357178           0.127408    0.028681
6            X_13           727.337585           0.114496    0.025775
7             X_2           718.571899           0.113117    0.025464
8             X_3           711.991211           0.112081    0.025231
9         DATEDay           703.013855           0.110667    0.024913
10           X_14           598.039612           0.094143    0.021193
11  DATEDayofyear           592.887390           0.093332    0.021010
12       DATEWeek           558.701965           0.087950    0.019799
13            X_6           544.719299           0.085749    0.019303
14            X_7           540.949341           0.085155    0.019170
15  DATEDayofweek           451.289124           0.071041    0.015992
16            X_4           417.636902           0.065744    0.014800
17      DATEMonth           399.042511           0.062817    0.014141
18            X_8           390.993439           0.061550    0.013856
19            X_9           374.669739           0.058980    0.013277

See the whole table with table.as_data_frame()

In [111]:
train=h2o.H2OFrame(train)
test=h2o.H2OFrame(test)

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%

In [112]:
train.columns

['INCIDENT_ID',
 'X_1',
 'X_2',
 'X_3',
 'X_4',
 'X_5',
 'X_6',
 'X_7',
 'X_8',
 'X_9',
 'X_10',
 'X_11',
 'X_12',
 'X_13',
 'X_14',
 'X_15',
 'MULTIPLE_OFFENSE',
 'DATEYear',
 'DATEMonth',
 'DATEWeek',
 'DATEDay',
 'DATEDayofweek',
 'DATEDayofyear',
 'DATEIs_month_end',
 'DATEIs_month_start',
 'DATEIs_quarter_end',
 'DATEIs_quarter_start',
 'DATEIs_year_end',
 'DATEIs_year_start',
 'DATEElapsed']

In [6]:
60*15

900

In [ ]:
# Import a sample binary outcome train/test set into H2O
#train = h2o.import_file("https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv")
#test = h2o.import_file("https://s3.amazonaws.com/erin-data/higgs/higgs_test_5k.csv")
import xgboost
# Identify predictors and response
x = train.columns
y = "MULTIPLE_OFFENSE"
x.remove(y)

# For binary classification, response should be a factor
train[y] = train[y].asfactor()
#test[y] = test[y].asfactor()

# Run AutoML for 20 base models (limited to 1 hour max runtime by default)
aml = H2OAutoML(max_models=20, seed=1,export_checkpoints_dir="../h2o",max_runtime_secs=)
aml.train(x=x, y=y, training_frame=train)

# View the AutoML Leaderboard
lb = aml.leaderboard
lb.head(rows=lb.nrows)  # Print all rows instead of default (10 rows)

AutoML progress: |ERROR! Session/line number was not unique in database. History logging moved to new session 335

15:14:35.472: AutoML: XGBoost is not available; skipping it.

██████████████████████████████████████████

In [8]:
lb

model_id,auc,logloss,aucpr,mean_per_class_error,rmse,mse
GBM_grid__1_AutoML_20200621_130655_model_1,0.999935,0.00217842,0.999997,0.00196042,0.0210321,0.00044235
GBM_1_AutoML_20200621_130655,0.999922,0.00262617,0.999996,0.0034088,0.0240163,0.000576785
GBM_grid__1_AutoML_20200621_130655_model_6,0.999909,0.00343807,0.999996,0.00525952,0.0260567,0.000678954
GBM_grid__1_AutoML_20200621_130655_model_3,0.999901,0.00393913,0.999995,0.00496689,0.0301303,0.000907837
GBM_2_AutoML_20200621_130655,0.999842,0.00369706,0.999992,0.00666401,0.0275301,0.000757907
GBM_4_AutoML_20200621_130655,0.999831,0.00437885,0.999992,0.00724189,0.0313399,0.000982192
GBM_3_AutoML_20200621_130655,0.999817,0.00438501,0.999991,0.00628361,0.0304074,0.000924612
GBM_grid__1_AutoML_20200621_130655_model_4,0.99978,0.00650153,0.99999,0.00579351,0.0378608,0.00143344
StackedEnsemble_BestOfFamily_AutoML_20200621_130655,0.999774,0.00377041,0.999989,0.00430125,0.0242833,0.00058968
GBM_grid__1_AutoML_20200621_130655_model_5,0.999752,0.0101719,0.999988,0.0130573,0.0458834,0.00210529
GBM_grid__1_AutoML_20200621_130655_model_2,0.999747,0.0116772,0.999988,0.01196,0.0527462,0.00278216
StackedEnsemble_AllModels_AutoML_20200621_130655,0.999705,0.00375941,0.999986,0.0048133,0.0253136,0.000640779
GBM_5_AutoML_20200621_130655,0.999672,0.0068457,0.999984,0.00931202,0.0396608,0.00157298
XRT_1_AutoML_20200621_130655,0.999277,0.0355281,0.999965,0.0308621,0.0819794,0.00672062
DRF_1_AutoML_20200621_130655,0.998221,0.0277307,0.999865,0.0200211,0.0777231,0.00604088
DeepLearning_1_AutoML_20200621_130655,0.959308,0.0864374,0.997434,0.256356,0.154077,0.0237398
DeepLearning_grid__1_AutoML_20200621_130655_model_1,0.955878,0.134687,0.996642,0.221873,0.147331,0.0217064
DeepLearning_grid__3_AutoML_20200621_130655_model_1,0.954902,0.115487,0.997219,0.324745,0.17067,0.0291281
DeepLearning_grid__2_AutoML_20200621_130655_model_1,0.951698,0.12876,0.996366,0.260094,0.155712,0.0242464
DeepLearning_grid__1_AutoML_20200621_130655_model_2,0.909392,0.141912,0.992591,0.359587,0.175502,0.0308008
GLM_1_AutoML_20200621_130655,0.88891,0.149027,0.993264,0.429555,0.190353,0.0362342
DeepLearning_grid__2_AutoML_20200621_130655_model_2,0.816853,0.312213,0.985483,0.460981,0.222507,0.0495094

In [10]:
preds = aml.predict(test)
preds

gbm prediction progress: |████████████████████████████████████████████████| 100%

predict,p0,p1
1,1.05951e-06,0.999999
1,7.38167e-08,1
1,9.52561e-07,0.999999
1,1.39921e-05,0.999986
1,1.60606e-07,1
1,7.90877e-08,1
1,5.74654e-07,0.999999
1,1.77869e-06,0.999998
1,1.95412e-06,0.999998
1,5.69944e-05,0.999943

In [14]:
predDF=preds.as_data_frame()
def addProb(df,k,prob):
    df[k+"_prob0"]=prob[:,0]
    df[k+"_prob1"]=prob[:,1]
    return df
pred=predDF['predict']

In [17]:
finalCheck=pd.read_csv("models_pred.csv")
finalCheck['h2o']=pred
finalCheck=addProb(finalCheck,"h2o",predDF.iloc[:,1:].values)
finalCheck[finalCheck['GB']!=finalCheck['catboost']]
#finalCheck.to_csv('models_pred.csv',index=False)

,RF,GB,RF_prob0,RF_prob1,GB_prob0,GB_prob1,catboost,catboost_prob0,catboost_prob1,h2o,h2o_prob0,h2o_prob1
356,0,0,0.53,0.47,0.654426,0.345574,1.0,0.341858,0.658142,0,0.147806,0.852194
965,0,0,0.75,0.25,0.643338,0.356662,1.0,0.465956,0.534044,0,0.166209,0.833791
1046,1,1,0.37,0.63,0.271686,0.728314,0.0,0.955325,0.044675,0,0.993451,0.006549
1146,1,0,0.31,0.69,0.551971,0.448029,1.0,0.075586,0.924414,1,0.014671,0.985329
1868,1,1,0.15,0.85,0.431913,0.568087,0.0,0.812064,0.187936,0,0.952312,0.047688
3314,1,1,0.37,0.63,0.229104,0.770896,0.0,0.768461,0.231539,0,0.975825,0.024175
4535,0,1,0.54,0.46,0.449659,0.550341,0.0,0.993636,0.006364,0,0.993014,0.006986
4759,1,0,0.47,0.53,0.566610,0.433390,1.0,0.168991,0.831009,1,0.045738,0.954262
4925,1,1,0.17,0.83,0.300280,0.699720,0.0,0.885531,0.114469,0,0.836920,0.163080
5182,0,1,0.53,0.47,0.415294,0.584706,0.0,0.649100,0.350900,0,0.721413,0.278587
7032,1,1,0.10,0.90,0.457666,0.542334,0.0,0.605892,0.394108,1,0.032678,0.967322
8001,0,0,0.53,0.47,0.653270,0.346730,1.0,0.472509,0.527491,0,0.144408,0.855592
8630,1,1,0.12,0.88,0.457666,0.542334,0.0,0.646048,0.353952,1,0.029942,0.970058
11564,1,1,0.11,0.89,0.262418,0.737582,0.0,0.689657,0.310343,0,0.762121,0.237879
12319,1,1,0.23,0.77,0.293524,0.706476,0.0,0.745342,0.254658,0,0.973441,0.026559
12872,1,0,0.41,0.59,0.541175,0.458825,1.0,0.089548,0.910452,1,0.012401,0.987599
13163,0,1,0.68,0.32,0.494238,0.505762,0.0,0.969457,0.030543,0,0.996716,0.003284
13688,0,0,0.59,0.41,0.541175,0.458825,1.0,0.046320,0.953680,1,0.010500,0.989500
13950,0,0,0.54,0.46,0.643338,0.356662,1.0,0.356166,0.643834,0,0.125182,0.874818
14521,1,1,0.47,0.53,0.271686,0.728314,0.0,0.974487,0.025513,0,0.988875,0.011125
14640,1,1,0.49,0.51,0.374606,0.625394,0.0,0.972688,0.027312,0,0.992716,0.007284
14861,0,1,0.54,0.46,0.456244,0.543756,0.0,0.952577,0.047423,0,0.998877,0.001123
15769,0,0,0.77,0.23,0.635135,0.364865,1.0,0.168541,0.831459,1,0.023141,0.976859

In [18]:
finalCheck[finalCheck['GB']!=finalCheck['h2o']]

,RF,GB,RF_prob0,RF_prob1,GB_prob0,GB_prob1,catboost,catboost_prob0,catboost_prob1,h2o,h2o_prob0,h2o_prob1
1046,1,1,0.37,0.63,0.271686,0.728314,0.0,0.955325,0.044675,0,0.993451,0.006549
1146,1,0,0.31,0.69,0.551971,0.448029,1.0,0.075586,0.924414,1,0.014671,0.985329
1234,1,1,0.34,0.66,0.325789,0.674211,1.0,0.166461,0.833539,0,0.652017,0.347983
1868,1,1,0.15,0.85,0.431913,0.568087,0.0,0.812064,0.187936,0,0.952312,0.047688
3314,1,1,0.37,0.63,0.229104,0.770896,0.0,0.768461,0.231539,0,0.975825,0.024175
4535,0,1,0.54,0.46,0.449659,0.550341,0.0,0.993636,0.006364,0,0.993014,0.006986
4759,1,0,0.47,0.53,0.566610,0.433390,1.0,0.168991,0.831009,1,0.045738,0.954262
4925,1,1,0.17,0.83,0.300280,0.699720,0.0,0.885531,0.114469,0,0.836920,0.163080
5182,0,1,0.53,0.47,0.415294,0.584706,0.0,0.649100,0.350900,0,0.721413,0.278587
7870,1,1,0.45,0.55,0.218373,0.781627,1.0,0.032173,0.967827,0,0.861431,0.138569
8232,1,1,0.46,0.54,0.419847,0.580153,1.0,0.376054,0.623946,0,0.866160,0.133840
8453,1,1,0.03,0.97,0.012642,0.987358,1.0,0.069357,0.930643,0,0.305362,0.694638
11564,1,1,0.11,0.89,0.262418,0.737582,0.0,0.689657,0.310343,0,0.762121,0.237879
12319,1,1,0.23,0.77,0.293524,0.706476,0.0,0.745342,0.254658,0,0.973441,0.026559
12872,1,0,0.41,0.59,0.541175,0.458825,1.0,0.089548,0.910452,1,0.012401,0.987599
13163,0,1,0.68,0.32,0.494238,0.505762,0.0,0.969457,0.030543,0,0.996716,0.003284
13688,0,0,0.59,0.41,0.541175,0.458825,1.0,0.046320,0.953680,1,0.010500,0.989500
14032,1,1,0.17,0.83,0.110940,0.889060,1.0,0.467931,0.532069,0,0.097947,0.902053
14521,1,1,0.47,0.53,0.271686,0.728314,0.0,0.974487,0.025513,0,0.988875,0.011125
14640,1,1,0.49,0.51,0.374606,0.625394,0.0,0.972688,0.027312,0,0.992716,0.007284
14861,0,1,0.54,0.46,0.456244,0.543756,0.0,0.952577,0.047423,0,0.998877,0.001123
15006,1,1,0.02,0.98,0.012642,0.987358,1.0,0.071308,0.928692,0,0.320053,0.679947
15769,0,0,0.77,0.23,0.635135,0.364865,1.0,0.168541,0.831459,1,0.023141,0.976859

In [19]:
finalCheck[finalCheck['catboost']!=finalCheck['h2o']]

,RF,GB,RF_prob0,RF_prob1,GB_prob0,GB_prob1,catboost,catboost_prob0,catboost_prob1,h2o,h2o_prob0,h2o_prob1
356,0,0,0.53,0.47,0.654426,0.345574,1.0,0.341858,0.658142,0,0.147806,0.852194
965,0,0,0.75,0.25,0.643338,0.356662,1.0,0.465956,0.534044,0,0.166209,0.833791
1234,1,1,0.34,0.66,0.325789,0.674211,1.0,0.166461,0.833539,0,0.652017,0.347983
7032,1,1,0.10,0.90,0.457666,0.542334,0.0,0.605892,0.394108,1,0.032678,0.967322
7870,1,1,0.45,0.55,0.218373,0.781627,1.0,0.032173,0.967827,0,0.861431,0.138569
8001,0,0,0.53,0.47,0.653270,0.346730,1.0,0.472509,0.527491,0,0.144408,0.855592
8232,1,1,0.46,0.54,0.419847,0.580153,1.0,0.376054,0.623946,0,0.866160,0.133840
8453,1,1,0.03,0.97,0.012642,0.987358,1.0,0.069357,0.930643,0,0.305362,0.694638
8630,1,1,0.12,0.88,0.457666,0.542334,0.0,0.646048,0.353952,1,0.029942,0.970058
13950,0,0,0.54,0.46,0.643338,0.356662,1.0,0.356166,0.643834,0,0.125182,0.874818
14032,1,1,0.17,0.83,0.110940,0.889060,1.0,0.467931,0.532069,0,0.097947,0.902053
15006,1,1,0.02,0.98,0.012642,0.987358,1.0,0.071308,0.928692,0,0.320053,0.679947

In [43]:
pred.shape

(15903,)

In [60]:
(((predDF['p1']<=0.47)*1)==pred).sum()
predDF[predDF['predict']==1]['p1'].max(),predDF[predDF['predict']==1]['p1'].min()
predDF[predDF['predict']==0]['p0'].max(),predDF[predDF['predict']==0]['p0'].min()

10

(0.9999999804505016, 0.9163704174753394)

(0.9999999994783126, 0.09794683954425644)

In [34]:
#finalCheck[['RF','GB','catboost','h2o']]
import numpy as np
finalCheck[['RF','GB','catboost','h2o']].apply(lambda x: np.unique(x,return_counts=True))

RF          ([0.0, 1.0], [616, 15287])
GB          ([0.0, 1.0], [718, 15185])
catboost    ([0.0, 1.0], [723, 15180])
h2o         ([0.0, 1.0], [731, 15172])
dtype: object

In [61]:
finalCheck[finalCheck['RF']==1]['RF_prob1'].max(),finalCheck[finalCheck['RF']==1]['RF_prob1'].min()
finalCheck[finalCheck['RF']==0]['RF_prob0'].max(),finalCheck[finalCheck['RF']==0]['RF_prob0'].min()

(1.0, 0.51)

(1.0, 0.5)

In [64]:
var='RF'
print(var)
finalCheck[finalCheck[f'{var}']==1][f'{var}_prob1'].max(),finalCheck[finalCheck[f'{var}']==1][f'{var}_prob1'].min()
finalCheck[finalCheck[f'{var}']==0][f'{var}_prob0'].max(),finalCheck[finalCheck[f'{var}']==0][f'{var}_prob0'].min()

var='GB'
print(var)
finalCheck[finalCheck[f'{var}']==1][f'{var}_prob1'].max(),finalCheck[finalCheck[f'{var}']==1][f'{var}_prob1'].min()
finalCheck[finalCheck[f'{var}']==0][f'{var}_prob0'].max(),finalCheck[finalCheck[f'{var}']==0][f'{var}_prob0'].min()

var='catboost'
print(var)
finalCheck[finalCheck[f'{var}']==1][f'{var}_prob1'].max(),finalCheck[finalCheck[f'{var}']==1][f'{var}_prob1'].min()
finalCheck[finalCheck[f'{var}']==0][f'{var}_prob0'].max(),finalCheck[finalCheck[f'{var}']==0][f'{var}_prob0'].min()

var='h2o'
print(var)
finalCheck[finalCheck[f'{var}']==1][f'{var}_prob1'].max(),finalCheck[finalCheck[f'{var}']==1][f'{var}_prob1'].min()
finalCheck[finalCheck[f'{var}']==0][f'{var}_prob0'].max(),finalCheck[finalCheck[f'{var}']==0][f'{var}_prob0'].min()

RF

(1.0, 0.51)

(1.0, 0.5)

GB

(0.9998214954728348, 0.5057616781732781)

(0.9988374307826002, 0.503330395801151)

catboost

(0.9999994526286364, 0.5274912359036681)

(0.9999996718784931, 0.6058924812242671)

h2o

(0.9999999804505016, 0.9163704174753394)

(0.9999999994783126, 0.09794683954425644)

In [83]:
thres=.62
finalCheck.shape
(((finalCheck['RF_prob1']>=thres)*1)==finalCheck['RF']).sum()
(((finalCheck['GB_prob1']>=thres)*1)==finalCheck['GB']).sum()
(((finalCheck['catboost_prob1']>=thres)*1)==finalCheck['catboost']).sum()
(((finalCheck['h2o_prob1']>=thres)*1)==finalCheck['h2o']).sum()

(15903, 12)

15808

15889

15899

15895

In [95]:
thres=0.47

In [96]:
finalCheck[(((finalCheck['RF_prob1']>=thres)*1)!=finalCheck['RF'])]
finalCheck[(((finalCheck['GB_prob1']>=thres)*1)!=finalCheck['GB'])]
finalCheck[(((finalCheck['catboost_prob1']>=thres)*1)!=finalCheck['catboost'])]
finalCheck[(((finalCheck['h2o_prob1']>=thres)*1)!=finalCheck['h2o'])]

,RF,GB,RF_prob0,RF_prob1,GB_prob0,GB_prob1,catboost,catboost_prob0,catboost_prob1,h2o,h2o_prob0,h2o_prob1
142,0,0,0.51,0.49,0.879453,0.120547,0.0,0.985412,0.014588,0,0.996568,0.003432
356,0,0,0.53,0.47,0.654426,0.345574,1.0,0.341858,0.658142,0,0.147806,0.852194
361,0,0,0.50,0.50,0.756714,0.243286,0.0,0.954633,0.045367,0,0.998976,0.001024
482,0,0,0.51,0.49,0.949278,0.050722,0.0,0.995228,0.004772,0,0.999105,0.000895
797,0,0,0.50,0.50,0.934443,0.065557,0.0,0.991306,0.008694,0,0.998751,0.001249
1058,0,0,0.50,0.50,0.868026,0.131974,0.0,0.973162,0.026838,0,0.996337,0.003663
1075,0,0,0.53,0.47,0.973928,0.026072,0.0,0.995352,0.004648,0,0.999644,0.000356
1361,0,0,0.51,0.49,0.893978,0.106022,0.0,0.983067,0.016933,0,0.996377,0.003623
1598,0,0,0.50,0.50,0.848873,0.151127,0.0,0.961979,0.038021,0,0.995207,0.004793
1669,0,0,0.53,0.47,0.793341,0.206659,0.0,0.980045,0.019955,0,0.999120,0.000880
1693,0,0,0.50,0.50,0.727844,0.272156,0.0,0.965542,0.034458,0,0.997595,0.002405
1702,0,0,0.53,0.47,0.992413,0.007587,0.0,0.998697,0.001303,0,0.999748,0.000252
1830,0,0,0.51,0.49,0.981222,0.018778,0.0,0.999233,0.000767,0,0.999364,0.000636
2805,0,0,0.52,0.48,0.934443,0.065557,0.0,0.992570,0.007430,0,0.999721,0.000279
2882,0,0,0.50,0.50,0.784176,0.215824,0.0,0.968940,0.031060,0,0.992675,0.007325
3290,0,0,0.53,0.47,0.911102,0.088898,0.0,0.994839,0.005161,0,0.985782,0.014218
3515,0,0,0.53,0.47,0.967658,0.032342,0.0,0.999944,0.000056,0,0.999917,0.000083
3577,0,0,0.52,0.48,0.739834,0.260166,0.0,0.977627,0.022373,0,0.998216,0.001784
3912,0,0,0.50,0.50,0.922599,0.077401,0.0,0.988463,0.011537,0,0.997642,0.002358
4981,0,0,0.50,0.50,0.992413,0.007587,0.0,0.998729,0.001271,0,0.999832,0.000168
5182,0,1,0.53,0.47,0.415294,0.584706,0.0,0.649100,0.350900,0,0.721413,0.278587
5424,0,0,0.51,0.49,0.849215,0.150785,0.0,0.913537,0.086463,0,0.994867,0.005133
5918,0,0,0.53,0.47,0.692188,0.307812,0.0,0.900870,0.099130,0,0.989722,0.010278
6042,0,0,0.51,0.49,0.964410,0.035590,0.0,0.998028,0.001972,0,0.999790,0.000210
6231,0,1,0.51,0.49,0.408141,0.591859,1.0,0.220309,0.779691,1,0.048105,0.951895
6650,0,1,0.52,0.48,0.198139,0.801861,1.0,0.044038,0.955962,1,0.009226,0.990774
7355,0,1,0.50,0.50,0.191408,0.808592,1.0,0.032809,0.967191,1,0.006183,0.993817
7534,0,0,0.51,0.49,0.675480,0.324520,0.0,0.985937,0.014063,0,0.994683,0.005317
7594,0,0,0.50,0.50,0.812193,0.187807,0.0,0.822026,0.177974,0,0.574116,0.425884
8001,0,0,0.53,0.47,0.653270,0.346730,0.0,0.472509,0.527491,0,0.144408,0.855592
8165,0,1,0.51,0.49,0.075508,0.924492,1.0,0.055128,0.944872,1,0.006570,0.993430
8845,0,0,0.53,0.47,0.922599,0.077401,0.0,0.947135,0.052865,0,0.990763,0.009237
8926,0,0,0.53,0.47,0.941492,0.058508,0.0,0.996013,0.003987,0,0.999712,0.000288
10015,0,1,0.53,0.47,0.307904,0.692096,1.0,0.130740,0.869260,1,0.013956,0.986044
10815,0,0,0.53,0.47,0.934443,0.065557,0.0,0.995122,0.004878,0,0.999333,0.000667
11165,0,1,0.50,0.50,0.220352,0.779648,1.0,0.038450,0.961550,1,0.006103,0.993897
11972,0,0,0.52,0.48,0.719479,0.280521,0.0,0.888553,0.111447,0,0.996891,0.003109
12043,0,1,0.52,0.48,0.107203,0.892797,1.0,0.033680,0.966320,1,0.006163,0.993837
12209,0,0,0.53,0.47,0.970684,0.029316,0.0,0.999973,0.000027,0,0.999995,0.000005
12800,0,0,0.51,0.49,0.922599,0.077401,0.0,0.986069,0.013931,0,0.995552,0.004448
13571,0,0,0.52,0.48,0.700673,0.299327,0.0,0.980436,0.019564,0,0.998957,0.001043
13621,0,0,0.52,0.48,0.911102,0.088898,0.0,0.989841,0.010159,0,0.997438,0.002562
13657,0,0,0.53,0.47,0.854377,0.145623,0.0,0.976771,0.023229,0,0.997966,0.002034

,RF,GB,RF_prob0,RF_prob1,GB_prob0,GB_prob1,catboost,catboost_prob0,catboost_prob1,h2o,h2o_prob0,h2o_prob1
945,1,0,0.21,0.79,0.522967,0.477033,0.0,0.887042,0.112958,0,0.941196,0.058804
4762,0,0,0.55,0.45,0.528004,0.471996,0.0,0.746022,0.253978,0,0.964784,0.035216
8369,1,0,0.19,0.81,0.522967,0.477033,0.0,0.875132,0.124868,0,0.956542,0.043458
8408,0,0,0.60,0.40,0.528184,0.471816,0.0,0.982802,0.017198,0,0.994079,0.005921
8416,0,0,0.63,0.37,0.503330,0.496670,0.0,0.913438,0.086562,0,0.451934,0.548066
8771,1,0,0.47,0.53,0.521587,0.478413,0.0,0.954844,0.045156,0,0.992876,0.007124
12811,1,0,0.27,0.73,0.512090,0.487910,0.0,0.928316,0.071684,0,0.936729,0.063271

,RF,GB,RF_prob0,RF_prob1,GB_prob0,GB_prob1,catboost,catboost_prob0,catboost_prob1,h2o,h2o_prob0,h2o_prob1
965,0,0,0.75,0.25,0.643338,0.356662,0.0,0.465956,0.534044,0,0.166209,0.833791
8001,0,0,0.53,0.47,0.653270,0.346730,0.0,0.472509,0.527491,0,0.144408,0.855592
13982,1,1,0.48,0.52,0.372223,0.627777,0.0,0.440596,0.559404,1,0.011051,0.988949
14032,1,1,0.17,0.83,0.110940,0.889060,0.0,0.467931,0.532069,0,0.097947,0.902053

,RF,GB,RF_prob0,RF_prob1,GB_prob0,GB_prob1,catboost,catboost_prob0,catboost_prob1,h2o,h2o_prob0,h2o_prob1
356,0,0,0.53,0.47,0.654426,0.345574,1.0,0.341858,0.658142,0,0.147806,0.852194
965,0,0,0.75,0.25,0.643338,0.356662,0.0,0.465956,0.534044,0,0.166209,0.833791
8001,0,0,0.53,0.47,0.653270,0.346730,0.0,0.472509,0.527491,0,0.144408,0.855592
8044,1,0,0.36,0.64,0.654426,0.345574,0.0,0.746626,0.253374,0,0.229250,0.770750
8416,0,0,0.63,0.37,0.503330,0.496670,0.0,0.913438,0.086562,0,0.451934,0.548066
8453,1,1,0.03,0.97,0.012642,0.987358,1.0,0.069357,0.930643,0,0.305362,0.694638
12472,1,0,0.33,0.67,0.562256,0.437744,0.0,0.783452,0.216548,0,0.419517,0.580483
13950,0,0,0.54,0.46,0.643338,0.356662,1.0,0.356166,0.643834,0,0.125182,0.874818
14032,1,1,0.17,0.83,0.110940,0.889060,0.0,0.467931,0.532069,0,0.097947,0.902053
15006,1,1,0.02,0.98,0.012642,0.987358,1.0,0.071308,0.928692,0,0.320053,0.679947

In [97]:
tweakpred=finalCheck['catboost']
tweakpred.iloc[finalCheck[(((finalCheck['catboost_prob1']>=thres)*1)!=finalCheck['catboost'])].index]=0

F:\anaconda\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [104]:
tweakpred1=finalCheck['h2o']
tweakpred1.iloc[finalCheck[(((finalCheck['h2o_prob1']>=thres)*1)!=finalCheck['h2o'])].index]=1

In [66]:
finalCheck.to_csv("models_pred.csv",index=False)

In [22]:
finalCheck=pd.read_csv('models_pred.csv')
finalCheck[['RF','GB','catboost','h2o']]

       RF  GB  catboost  h2o
0       1   1       1.0    1
1       1   1       1.0    1
2       1   1       1.0    1
3       1   1       1.0    1
4       1   1       1.0    1
5       1   1       1.0    1
6       1   1       1.0    1
7       1   1       1.0    1
8       1   1       1.0    1
9       1   1       1.0    1
10      1   1       1.0    1
11      1   1       1.0    1
12      1   1       1.0    1
13      1   1       1.0    1
14      1   1       1.0    1
15      1   1       1.0    1
16      1   1       1.0    1
17      1   1       1.0    1
18      0   0       0.0    0
19      1   1       1.0    1
20      1   1       1.0    1
21      1   1       1.0    1
22      1   1       1.0    1
23      1   1       1.0    1
24      1   1       1.0    1
25      1   1       1.0    1
26      1   1       1.0    1
27      1   1       1.0    1
28      1   1       1.0    1
29      1   1       1.0    1
...    ..  ..       ...  ...
15873   1   1       1.0    1
15874   1   1       1.0    1
15875   1   1       1.0    1
15876   1   1       1.0    1
15877   1   1       1.0    1
15878   1   1       1.0    1
15879   1   1       1.0    1
15880   1   1       1.0    1
15881   1   1       1.0    1
15882   1   1       1.0    1
15883   1   1       1.0    1
15884   1   1       1.0    1
15885   1   1       1.0    1
15886   1   1       1.0    1
15887   1   1       1.0    1
15888   1   1       1.0    1
15889   1   1       1.0    1
15890   1   1       1.0    1
15891   1   1       1.0    1
15892   1   1       1.0    1
15893   1   1       1.0    1
15894   1   1       1.0    1
15895   1   1       1.0    1
15896   1   1       1.0    1
15897   1   1       1.0    1
15898   1   1       1.0    1
15899   1   1       1.0    1
15900   1   1       1.0    1
15901   1   1       1.0    1
15902   1   1       1.0    1

[15903 rows x 4 columns]

In [24]:
from sklearn.ensemble import VotingClassifier
vc=VotingClassifier([],voting='hard')
#vc.transform(finalCheck[['RF','GB','catboost','h2o']])

In [109]:
from sklearn.base import BaseEstimator,ClassifierMixin
from sklearn.ensemble._voting import _BaseVoting
class FromFileClassifier(BaseEstimator,ClassifierMixin):
    def __init__(self,filePath,columnName='RF'):
        super(FromFileClassifier,self).__init__()
        self.filePath=filePath
        self.columnName=columnName
        self.data=pd.read_csv(self.filePath).astype(float)
    def fit(self,X,Y):
        return self
    def predict(self,X):
        """
        X is dummy here
        """
        predCols=self.data.columns[self.data.columns.str.startswith(self.columnName)]
        print(predCols)
        #preds.append(self.data[predCols[0]])
        #print(self.data[predCols[0]].values)
        return self.data[predCols[0]].values
    
    def predict_proba(self,X):
        predCols=self.data.columns[self.data.columns.str.startswith(self.columnName)]
        #probhas.append(self.data[predCols[1:]].values)
        #print(self.data[predCols[1:]].values)
        return self.data[predCols[1:]].values
    
    
clfs=[(clf,FromFileClassifier("models_pred.csv",columnName=clf)) for clf in ["RF","GB","catboost","h2o"]]
vclf=VotingClassifier(estimators=clfs,voting='hard')
vclf.fit(train.iloc[:,1:].values,train.iloc[:,-1].values)
vclf.predict(train.iloc[:,1:])

VotingClassifier(estimators=[('RF',
                              FromFileClassifier(filePath='models_pred.csv')),
                             ('GB',
                              FromFileClassifier(columnName='GB',
                                                 filePath='models_pred.csv')),
                             ('catboost',
                              FromFileClassifier(columnName='catboost',
                                                 filePath='models_pred.csv')),
                             ('h2o',
                              FromFileClassifier(columnName='h2o',
                                                 filePath='models_pred.csv'))])

Index(['RF', 'RF_prob0', 'RF_prob1'], dtype='object')
Index(['GB', 'GB_prob0', 'GB_prob1'], dtype='object')
Index(['catboost', 'catboost_prob0', 'catboost_prob1'], dtype='object')
Index(['h2o', 'h2o_prob0', 'h2o_prob1'], dtype='object')

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [128]:
from sklearn.utils.validation import _deprecate_positional_args
from sklearn.utils.multiclass import check_classification_targets
#from ..utils.validation import _deprecate_positional_args

class WrapVotingClassifier(ClassifierMixin, _BaseVoting):
    
    @_deprecate_positional_args
    def __init__(self, estimators, *, voting='hard', weights=None,
                 n_jobs=None, flatten_transform=True, verbose=False):
        super().__init__(estimators=estimators)
        self.voting = voting
        self.weights = weights
        self.n_jobs = n_jobs
        self.flatten_transform = flatten_transform
        self.verbose = verbose

    def fit(self, X, y, sample_weight=None):
        """Fit the estimators.
        Parameters
        ----------
        X : {array-like, sparse matrix} of shape (n_samples, n_features)
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.
        y : array-like of shape (n_samples,)
            Target values.
        sample_weight : array-like of shape (n_samples,), default=None
            Sample weights. If None, then samples are equally weighted.
            Note that this is supported only if all underlying estimators
            support sample weights.
            .. versionadded:: 0.18
        Returns
        -------
        self : object
        """
        check_classification_targets(y)
        if isinstance(y, np.ndarray) and len(y.shape) > 1 and y.shape[1] > 1:
            raise NotImplementedError('Multilabel and multi-output'
                                      ' classification is not supported.')

        if self.voting not in ('soft', 'hard'):
            raise ValueError("Voting must be 'soft' or 'hard'; got (voting=%r)"
                             % self.voting)

        #self.le_ = LabelEncoder().fit(y)
        #self.classes_ = self.le_.classes_
        #transformed_y = self.le_.transform(y)
        self.estimators_=[est[1] for est in self.estimators]
        return self #super().fit(X, transformed_y, sample_weight)

    def predict(self, X):
        """Predict class labels for X.
        Parameters
        ----------
        X : {array-like, sparse matrix} of shape (n_samples, n_features)
            The input samples.
        Returns
        -------
        maj : array-like of shape (n_samples,)
            Predicted class labels.
        """
        #check_is_fitted(self)
        if self.voting == 'soft':
            maj = np.argmax(self.predict_proba(X), axis=1)

        else:  # 'hard' voting
            
            predictions = self._predict(X)
            maj = np.apply_along_axis(
                lambda x: np.argmax(
                    np.bincount(x, weights=None)),
                axis=1, arr=predictions)

        #maj = self.le_.inverse_transform(maj)

        return maj

    def _collect_probas(self, X):
        """Collect results from clf.predict calls."""
        return np.asarray([clf.predict_proba(X) for clf in self.estimators_])

    def _predict_proba(self, X):
        """Predict class probabilities for X in 'soft' voting."""
        #check_is_fitted(self)
        avg = np.average(self._collect_probas(X), axis=0,
                         weights=self._weights_not_none)
        return avg

    @property
    def predict_proba(self):
        """Compute probabilities of possible outcomes for samples in X.
        Parameters
        ----------
        X : {array-like, sparse matrix} of shape (n_samples, n_features)
            The input samples.
        Returns
        -------
        avg : array-like of shape (n_samples, n_classes)
            Weighted average probability for each class per sample.
        """
        if self.voting == 'hard':
            raise AttributeError("predict_proba is not available when"
                                 " voting=%r" % self.voting)
        return self._predict_proba

    def transform(self, X):
        """Return class labels or probabilities for X for each estimator.
        Parameters
        ----------
        X : {array-like, sparse matrix} of shape (n_samples, n_features)
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.
        Returns
        -------
        probabilities_or_labels
            If `voting='soft'` and `flatten_transform=True`:
                returns ndarray of shape (n_classifiers, n_samples *
                n_classes), being class probabilities calculated by each
                classifier.
            If `voting='soft' and `flatten_transform=False`:
                ndarray of shape (n_classifiers, n_samples, n_classes)
            If `voting='hard'`:
                ndarray of shape (n_samples, n_classifiers), being
                class labels predicted by each classifier.
        """
        #check_is_fitted(self)

        if self.voting == 'soft':
            probas = self._collect_probas(X)
            if not self.flatten_transform:
                return probas
            return np.hstack(probas)

        else:
            return self._predict(X)

In [130]:
clfs=[(clf,FromFileClassifier("models_pred.csv",columnName=clf)) for clf in ["RF","GB","catboost","h2o"]]
vclf=WrapVotingClassifier(estimators=clfs,voting='soft')
vclf.fit(train.iloc[:,1:].values,train.iloc[:,-1].values)
votePred=vclf.predict(train.iloc[:,1:])

WrapVotingClassifier(estimators=[('RF',
                                  FromFileClassifier(filePath='models_pred.csv')),
                                 ('GB',
                                  FromFileClassifier(columnName='GB',
                                                     filePath='models_pred.csv')),
                                 ('catboost',
                                  FromFileClassifier(columnName='catboost',
                                                     filePath='models_pred.csv')),
                                 ('h2o',
                                  FromFileClassifier(columnName='h2o',
                                                     filePath='models_pred.csv'))],
                     voting='soft')

In [131]:
np.unique(votePred,return_counts=True)

(array([0, 1], dtype=int64), array([  721, 15182], dtype=int64))

In [55]:
finalCheck.columns[finalCheck.columns.str.startswith('RF')]
finalCheck.columns[finalCheck.columns.str.startswith('GB')]
finalCheck.columns[finalCheck.columns.str.startswith('catboost')]
finalCheck.columns[finalCheck.columns.str.startswith('h2o')]

Index(['RF', 'RF_prob0', 'RF_prob1'], dtype='object')

Index(['GB', 'GB_prob0', 'GB_prob1'], dtype='object')

Index(['catboost', 'catboost_prob0', 'catboost_prob1'], dtype='object')

Index(['h2o', 'h2o_prob0', 'h2o_prob1'], dtype='object')

In [34]:
predictions = finalCheck[['RF','GB','catboost','h2o']]
predictions[predictions.sum(axis=1)!=4]

       RF  GB  catboost  h2o
18      0   0       0.0    0
40      0   0       0.0    0
71      0   0       0.0    0
99      0   0       0.0    0
105     0   0       0.0    0
110     0   0       0.0    0
112     0   0       0.0    0
114     0   0       0.0    0
125     0   0       0.0    0
138     0   0       0.0    0
142     0   0       0.0    0
192     0   0       0.0    0
199     1   0       0.0    0
202     1   0       0.0    0
207     0   0       0.0    0
216     0   0       0.0    0
229     0   0       0.0    0
230     0   0       0.0    0
238     1   0       0.0    0
248     1   0       0.0    0
264     0   0       0.0    0
297     0   0       0.0    0
356     0   0       1.0    0
361     0   0       0.0    0
382     0   0       0.0    0
436     0   0       0.0    0
458     0   0       0.0    0
473     1   0       0.0    0
482     0   0       0.0    0
509     0   0       0.0    0
...    ..  ..       ...  ...
15036   0   0       0.0    0
15130   0   0       0.0    0
15133   0   0       0.0    0
15149   0   0       0.0    0
15187   0   0       0.0    0
15195   0   0       0.0    0
15206   0   0       0.0    0
15221   0   0       0.0    0
15226   0   0       0.0    0
15250   0   0       0.0    0
15268   0   0       0.0    0
15282   0   0       0.0    0
15286   0   0       0.0    0
15340   0   0       0.0    0
15407   0   1       1.0    1
15435   0   0       0.0    0
15454   1   0       0.0    0
15459   1   0       0.0    0
15469   1   0       0.0    0
15471   0   0       0.0    0
15485   0   0       0.0    0
15491   0   0       0.0    0
15517   0   0       0.0    0
15526   0   0       0.0    0
15554   0   0       0.0    0
15769   0   0       1.0    1
15775   1   0       0.0    0
15787   1   0       0.0    0
15824   0   0       0.0    0
15825   0   0       0.0    0

[754 rows x 4 columns]

In [139]:


def majVote(x):
    s=x.sum()
    ones=s
    zeros=4-ones
    #print(s,ones,zeros)
    
    if zeros>ones:
        res=0
    else:
        res=1
    return res
voteHard=finalCheck[['RF','GB','catboost','h2o']].apply(lambda x:majVote(x),axis=1)

In [144]:
dict('n_estimators'=100)

SyntaxError: keyword can't be an expression (<ipython-input-144-7c7f2102a66a>, line 1)

In [140]:
np.unique(voteHard,return_counts=True)

(array([0, 1], dtype=int64), array([  717, 15186], dtype=int64))

In [141]:
subDF=pd.DataFrame(columns=["INCIDENT_ID","MULTIPLE_OFFENSE"])
subDF['INCIDENT_ID']=test['INCIDENT_ID']
subDF['MULTIPLE_OFFENSE']=voteHard
#subDF.set_index("INCIDENT_ID",drop=True,inplace=True)
subDF.to_csv("submission_tweaked_hardVote.csv",index=False)